'use client';
import {useEffect,useRef,useState} from 'react';
import Avatar from './Avatar';
import {basicTutor} from '../lib/basicTutor';
import {loadProgress,saveMistake,saveProgress} from '../lib/storage';

type Msg={role:'you'|'tutor';text:string};
export default function VideoTutor(){
 const [messages,setMessages]=useState<Msg[]>([{role:'tutor',text:"Hi! I'm Emma. Tell me about your day."}]);
 const [listening,setListening]=useState(false);const [speaking,setSpeaking]=useState(false);const [correction,setCorrection]=useState<{a:string,b:string,c:string}|null>(null);const [aiState,setAiState]=useState<'basic'|'loading'|'local'>('basic');const engineRef=useRef<any>(null);
 const speechRef=useRef<any>(null);
 useEffect(()=>{return()=>{speechRef.current?.stop?.();speechSynthesis?.cancel?.()}},[]);
 const speak=(text:string)=>{if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.96;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);speechSynthesis.speak(u)};
 const localReply=async(input:string)=>{if(!engineRef.current)return null;const sys=`You are Emma, a friendly British English tutor. Reply briefly in natural English. If the learner makes a meaningful grammar or word-choice error, first continue the conversation naturally, then add exactly two lines: CORRECTION: <corrected sentence> and WHY: <short explanation in Portuguese>. Do not over-correct punctuation.`;const out=await engineRef.current.chat.completions.create({messages:[{role:'system',content:sys},{role:'user',content:input}],temperature:.7,max_tokens:180});return out.choices?.[0]?.message?.content||null};
 const handleInput=async(text:string)=>{if(!text.trim())return;setMessages(m=>[...m,{role:'you',text}]);let reply='';let corr:any=null;
  if(engineRef.current){try{const raw=await localReply(text);if(raw){const cm=raw.match(/CORRECTION:\s*(.+)/i);const wm=raw.match(/WHY:\s*(.+)/i);reply=raw.split(/CORRECTION:/i)[0].trim();if(cm&&wm)corr={a:text,b:cm[1].trim(),c:wm[1].trim()};}}catch{} }
  if(!reply){const r=basicTutor(text);reply=r.reply;if(r.corrected&&r.why)corr={a:text,b:r.corrected,c:r.why};}
  setMessages(m=>[...m,{role:'tutor',text:reply}]);if(corr){setCorrection(corr);saveMistake({heard:corr.a,corrected:corr.b,why:corr.c});const p=loadProgress();p.corrections++;saveProgress(p);} speak(reply);
 };
 const listen=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert('Reconhecimento de voz não está disponível neste navegador. Use Chrome/Edge recente ou digite a frase.');return;}const r=new SR();speechRef.current=r;r.lang='en-GB';r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>handleInput(e.results[0][0].transcript);r.start();};
 const enableLocalAI=async()=>{setAiState('loading');try{const webllm=await import('@mlc-ai/web-llm');if(!('gpu'in navigator))throw new Error('WebGPU indisponível');const candidates=webllm.prebuiltAppConfig.model_list.map((x:any)=>x.model_id);const id=candidates.find((x:string)=>/Qwen2.*0\.5B.*Instruct/i.test(x))||candidates.find((x:string)=>/Qwen.*0\.5B/i.test(x))||candidates.find((x:string)=>/SmolLM2.*360M/i.test(x));if(!id)throw new Error('Modelo leve não encontrado');engineRef.current=await webllm.CreateMLCEngine(id,{initProgressCallback:(p:any)=>{const el=document.getElementById('modelProgress');if(el)el.textContent=p.text||'Carregando modelo...';}});setAiState('local');}catch(e){console.error(e);setAiState('basic');alert('Este aparelho/navegador não conseguiu carregar a IA local. O modo básico continua funcionando sem API.');}};
 return <div className="card call"><div className="callHead"><div><b>Emma 🇬🇧</b><div className="small muted"><span className="statusDot"/>British English Tutor</div></div><span className="badge">{aiState==='local'?'IA local ativa':aiState==='loading'?'Carregando IA local…':'Modo básico'}</span></div><div className="avatarStage"><Avatar speaking={speaking}/></div><div className="transcript">{messages.slice(-6).map((m,i)=><div className="bubble" key={i}><b>{m.role==='you'?'You':'Emma'}:</b> {m.text}</div>)}</div>{correction&&<div className="correction"><div className="small muted">Você disse</div><div>{correction.a}</div><div className="small muted" style={{marginTop:8}}>Forma corrigida</div><div className="success">{correction.b}</div><div className="small muted" style={{marginTop:8}}>{correction.c}</div></div>}<div className="actions"><button className="btn primary" onClick={listen}>{listening?'🎙 Listening…':'🎙 Speak'}</button><button className="btn" onClick={()=>speak(messages.filter(m=>m.role==='tutor').at(-1)?.text||'Hello!')}>🔊 Replay</button><button className="btn" onClick={enableLocalAI} disabled={aiState!=='basic'}>{aiState==='basic'?'🧠 Enable local AI':'🧠 Local AI'}</button></div>{aiState==='loading'&&<div id="modelProgress" className="small warning">Preparando download do modelo local…</div>}</div>
}
